apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "the-flagrant-fowl.fullname" . }}
  labels: {{ include "the-flagrant-fowl.labels" . | nindent 4 }}

spec:
  progressDeadlineSeconds: 300
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels: {{ include "the-flagrant-fowl.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels: {{ include "the-flagrant-fowl.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: VERSION
          value: {{ .Chart.AppVersion }}
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.aws.region }}
        - name: AWS_SECRET_NAME
          value: {{ .Values.aws.secretName }}
        {{- if eq .Values.env "dev" }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ .Values.aws.accessKeyId }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ .Values.aws.secretAccessKey }}
        {{- end }}
      {{- if eq .Values.env "dev" }}
        image: "{{ .Values.image.name}}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Never
      {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
      {{- end }}
        name: the-flagrant-fowl
        ports:
        - containerPort: {{ .Values.containerPort }}
          name: {{ include "the-flagrant-fowl.targetPort" . }}
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        resources: {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          exec:
            command:
            - cat
            - /app/package.json
          initialDelaySeconds: 5
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ include "the-flagrant-fowl.targetPort" . }}
          initialDelaySeconds: 5
          failureThreshold: 6
          periodSeconds: 10
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "the-flagrant-fowl.serviceAccountName" . }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
